name: Questly CI/CD dev

on:
  push:
    branches: [ "main" ]

jobs:
  # Job для сборки и анализа кода
  build-and-analyze:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 📦 Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner

      - name: 🧰 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: 🧪 Start SonarCloud analysis
        # Sonar AI Code Assurance is a verification process for detecting AI-generated code
        # and then running it through a structured and comprehensive analysis.
        # This ensures all new code meets the highest standards of quality and security.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin \
            /k:"ShdwKick_Questly" \
            /o:"burninghouse" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.cs.dotcover.reportsPaths="**/coverage.opencover.xml"
      
      - name: 🔨 Build and analyze project
        run: |
          dotnet restore ${{ vars.SOLUTION_NAME }}
          dotnet build ${{ vars.SOLUTION_NAME }} --configuration Debug --no-restore
      
      - name: 🧪 Finish SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner end \
            /d:sonar.token="$SONAR_TOKEN"

  # Job для сборки и публикации Docker образов
  build-and-push:
    runs-on: ubuntu-latest
    environment: env
    needs: build-and-analyze
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 🛠 Build Questly image
        run: docker build -t ${{ vars.QUESTLY_IMAGE }} -f Questly/Dockerfile .
          
      - name: 🚀 Push Questly image
        run: docker push ${{ vars.QUESTLY_IMAGE }}:latest

  deploy:
    runs-on: ubuntu-latest
    environment: env
    needs: build-and-push
    steps:
      - name: 🧬 Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "vm.swappiness=30" | sudo tee -a /etc/sysctl.conf
            sudo sysctl -p
            cd /root/QuestlyCompose

            cat > .env <<EOF
              POSTGRES_USER=${{ vars.POSTGRES_USER }}
              POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}
              POSTGRES_DB=${{ vars.POSTGRES_DB }}
              SERVER_KEY=${{ vars.SERVER_KEY }}
              HASH_SALT=${{ vars.HASH_SALT }}
              ISSUER=${{ vars.ISSUER }}
              AUDIENCE=${{ vars.AUDIENCE }}
              CONNECTION_STRING=${{ vars.CONNECTION_STRING }}
              RABBITMQ_USERNAME=${{ vars.RABBITMQ_USERNAME }}
              RABBITMQ_PASSWORD=${{ vars.RABBITMQ_PASSWORD }}
              RABBITMQ_HOSTNAME=${{ vars.RABBITMQ_HOSTNAME }}
            EOF
            
            docker compose down --remove-orphans
            docker compose pull
            docker compose up -d --build
